//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name = "#")]
        public int id { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(50, ErrorMessage = "El nombre no puede tener más de 50 caracteres.")]
        public string name { get; set; }

        [Display(Name = "Position")]
        [Required(ErrorMessage = "El puesto es obligatorio.")]
        [StringLength(50, ErrorMessage = "El puesto no puede tener más de 50 caracteres.")]
        public string position { get; set; }

        [Display(Name = "Office")]
        [Required(ErrorMessage = "La oficina es obligatoria.")]
        [StringLength(50, ErrorMessage = "La oficina no puede tener más de 50 caracteres.")]
        public string office { get; set; }

        [Display(Name = "Salary")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        [Required(ErrorMessage = "El salario es obligatorio")]
        public decimal salary { get; set; }
    }
}
